import Head from "next/head";
import Image from "next/image";
import PlantsList from "../components/plants";
import Menu from "../components/pl-menu";
import Footer from "../components/pl-footer";
import Link from "next/link";

export default function Database() {
  return (
    <div>
      <Head>
        <title>Plants Project Live</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header>
        <Menu />
      </header>
      <div className='container mx-auto'>
        <h1 className='text-3xl font-bold my-8 leading-tight'>
          Collection Database
        </h1>
      </div>
      <div>
        <PlantsList />
      </div>
      <footer>
        <Footer />
      </footer>
    </div>
  );
}
