import Head from 'next/head'
import Image from 'next/image'
import PlantsList from '../components/plants'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Plants Project Live</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1 className='text-4xl text-center py-12'>
          Plants Database
        </h1>   
      </div>
      <div>
      <PlantsList  />
      </div>
      
    </div>
  )
}
