import Head from 'next/head'
import Image from 'next/image'
import Menu from '../components/pl-menu'
import Footer from '../components/pl-footer'
import Link from 'next/link'
import ConPlan from '../components/form'

export default function Mentor() {
  return (
    <div className='h-screen'>
      <Head>
        <title>Plants Project Live</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Menu />
      </header>
      <div className='container mx-auto'>
        <h1 className='text-4xl text-center py-12 font-Novel uppercase'>
          Mentorship Application
        </h1>  
        <ConPlan /> 
      </div>
      <div>
     
      </div>
      <footer><Footer /></footer>
    </div>
  )
}
