import React, { Component} from 'react';
const token = "keykEQO9bMo2Fukln";
import Image from 'next/image';
import Head from 'next/head'
import { data } from 'autoprefixer';

class MPlants extends Component {

  constructor(props) {
    super(props);
    this.state = {
      plants: []
    };
  }

  componentDidMount() {
    const plants = this.state.plants;
    fetch("https://api.airtable.com/v0/appFj2Envr91ItMKQ/Plants",  {
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${token}`,
      },
    })
    .then((resp) => resp.json())
    .then(data => {
      const plant = data.records;
      plants.push(plant)
      console.log(plants)
      // for (var i = 0; i < plant.length; i++) {
      //   // console.log(plant[i]);
      //   // currentPlants.push(data)
        
      //   // console.log(plant)
      //   // console.log(plants)
      // }
      
    })
    // .then(data => this.setState({ plants: data.plants }))
    .catch(err => {
      // Error
    });
    this.setState({'plants': plants })
    
  }
  
  render() {
  
    return (
      
      <div >
      <Head>
        <title>Plants project live</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>
          Hey You
          {this.state.plants.map((plants) => (
            <div key={plants.id} className="max-w-sm rounded overflow-hidden shadow-lg transform transition duration-300 hover:scale-105">
                <div className="px-6 py-4">
                  <div key={plants.id} className="font-bold text-xl mb-2">Name: {plants.Name}</div>
                    <p className="text-gray-700 text-base">
                   Personality: {plants.Personality}
                    </p>
                </div>
                <div key={plants.id} className="px-6 pb-5">
                  <a>Care: {plants.Care}</a>
                </div>
            </div>
          ))}
          
        </h1>

        

        
      </div>
    </div>
 
    );
  }
}

export default MPlants;
