import Head from "next/head";
import Sub from "../components/forms";
import Menu from "../components/pl-menu";
import Footer from "../components/pl-footer";

export default function Subs() {
  return (
    <div className='font-Novel text-xl'>
      <Head>
        <title>Plants Project Live</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header>
        <Menu />
      </header>
      <div className='container mx-auto h-2/3'>
        <h1 className='text-4xl text-center py-12 font-Novel uppercase'>
          Plant Submissions
        </h1>
        <p className='text-xl font-Novel '>
          Discover and share your collection of house plants, connect with
          interesting people, and work together to help new plant parents in
          need. Im baby pok pok fingerstache 90s, vice artisan +1 pitchfork.
          Chambray shaman air plant selvage, banjo mlkshk cray migas yuccie
          brooklyn seitan raw denim lyft glossier narwhal. Sartorial mustache
          humblebrag snackwave. Selvage umami vape, DIY mlkshk locavore trust
          fund shaman try-hard direct trade fingerstache craft beer. Freegan
          lomo street art, blue bottle locavore etsy trust fund offal squid
          godard marfa.{" "}
        </p>
        <div className='container mx-auto'>
          <Sub />
        </div>
      </div>

      <Footer />
    </div>
  );
}
